*** Comments ***
Generated firmware running REAL Embedded Coder model code (closes O-9).

Every earlier generated-firmware suite ran hand-written stand-ins in place
of model code. This one runs the genuine article: FastCtrl and ThermalModel
are compiled by Embedded Coder from the .slx fixtures, bound to the RTE by
generated adapters, and cross-wired both directions —

    hal.hal_adc_read      -> FastCtrl.adc_u        (HAL into the fast loop)
    FastCtrl.torque_cmd   -> ThermalModel.load_in  (fast -> slow, seqlock)
    ThermalModel.derate_pct -> FastCtrl.derate_in  (slow -> fast, seqlock)

so the loop closes through ERT code on both sides of two rate boundaries.

Telemetry line (generated by rte_gen.c):
  RTEGEN hb=<n> dhb=<n> exec_max=<n> ovr=<n> slf=<n> slow_100ms=<n>
         daq=<n> daq_drain=<n> FastCtrl_torque_cmd=<v> ThermalModel_derate_pct=<v>

*** Settings ***
Suite Setup                   Setup
Suite Teardown                Teardown
Test Teardown                 Test Teardown
Resource                      ${RENODEKEYWORDS}

*** Variables ***
${FIRMWARE}                   ${CURDIR}${/}..${/}build-ert${/}picodesk_gen_firmware.elf

*** Keywords ***
Prepare Machine
    Execute Command           $global.FIRMWARE=@${FIRMWARE}
    Execute Script            ${CURDIR}${/}picodesk_sim.resc
    Create Terminal Tester    sysbus.uart0    timeout=60    defaultPauseEmulation=true

Read Telemetry
    ${line}=    Wait For Line On Uart    RTEGEN hb=
    RETURN                    ${line['Line']}

*** Test Cases ***
ERT Generated Models Run In The RTE
    [Documentation]           Real Embedded Coder code dispatches under the
    ...                       generated RTE: 1 kHz fast group with no
    ...                       overruns (RTE-002), the slow group firing at
    ...                       its divider, no seqlock stale fallbacks
    ...                       (RTE-004) and the DAQ ring streaming (RTE-005).
    Prepare Machine
    Wait For Line On Uart     PicoDesk generated RTE boot
    Read Telemetry
    ${line}=    Read Telemetry
    ${m}=    Evaluate    re.search(r"hb=(\\d+) dhb=(\\d+) exec_max=(\\d+) ovr=(\\d+) slf=(\\d+) slow_100ms=(\\d+) daq=(\\d+)", $line)    re
    Should Not Be Equal       ${m}    ${None}    msg=unparseable: ${line}

    ${dhb}=    Evaluate       int($m.group(2))
    ${ovr}=    Evaluate       int($m.group(4))
    ${slf}=    Evaluate       int($m.group(5))
    ${s100}=   Evaluate       int($m.group(6))
    ${daq}=    Evaluate       int($m.group(7))
    Should Be True            900 <= ${dhb} <= 1100    msg=fast rate off: ${dhb}
    Should Be Equal As Integers    ${ovr}    0    msg=overruns with ERT code
    Should Be Equal As Integers    ${slf}    0    msg=seqlock stale fallbacks
    Should Be True            ${s100} > 0    msg=100 ms group not firing
    Should Be True            ${daq} > 0     msg=DAQ ring not streaming

ERT Cross-Core Loop Closes Through Both Seqlock Buses
    [Documentation]           ThermalModel derates FastCtrl's torque, and
    ...                       FastCtrl's torque drives ThermalModel — through
    ...                       one seqlock bus each way. A nonzero derate
    ...                       proves the slow ERT model consumed fast-loop
    ...                       output and its result reached the fast loop
    ...                       (RTE-001, RTE-004).
    Prepare Machine
    Wait For Line On Uart     PicoDesk generated RTE boot
    Read Telemetry
    Read Telemetry
    ${line}=    Read Telemetry
    ${torque}=    Evaluate
    ...    int(re.search(r"FastCtrl_torque_cmd=(-?\\d+)", $line).group(1))    re
    ${derate}=    Evaluate
    ...    int(re.search(r"ThermalModel_derate_pct=(-?\\d+)", $line).group(1))    re
    Should Not Be Equal As Integers    ${torque}    0
    ...                       msg=ERT fast model produced no output
    Should Be True            ${derate} > 0
    ...                       msg=cross-core round trip through ERT code broken
