*** Comments ***
Generated firmware running REAL Embedded Coder model code (closes O-9).

Every earlier generated-firmware suite ran hand-written stand-ins in place
of model code. This one runs the genuine article: FastCtrl and ThermalModel
are compiled by Embedded Coder from the .slx fixtures, bound to the RTE by
generated adapters, and cross-wired both directions —

    hal.hal_adc_read      -> FastCtrl.adc_u        (HAL into the fast loop)
    FastCtrl.torque_cmd   -> ThermalModel.load_in  (fast -> slow, seqlock)
    ThermalModel.derate_pct -> FastCtrl.derate_in  (slow -> fast, seqlock)

so the loop closes through ERT code on both sides of two rate boundaries.

Telemetry line (generated by rte_gen.c):
  RTEGEN hb=<n> dhb=<n> exec_max=<n> ovr=<n> slf=<n> slow_100ms=<n>
         daq=<n> daq_drain=<n> FastCtrl_torque_cmd=<v> ThermalModel_derate_pct=<v>

*** Settings ***
Suite Setup                   Setup
Suite Teardown                Teardown
Test Teardown                 Test Teardown
Resource                      ${RENODEKEYWORDS}
Resource                      ${CURDIR}${/}telemetry.resource

*** Variables ***
${FIRMWARE}                   ${CURDIR}${/}..${/}build-ert${/}picodesk_gen_firmware.elf

*** Keywords ***
Prepare Machine
    Execute Command           $global.FIRMWARE=@${FIRMWARE}
    Execute Script            ${CURDIR}${/}picodesk_sim.resc
    Create Terminal Tester    sysbus.uart0    timeout=60    defaultPauseEmulation=true

Read Telemetry
    [Documentation]           Returns (line, parsed fields).
    ${line}=    Wait For Line On Uart    RTEGEN hb=
    ${t}=                     Parse Telemetry Fields    ${line['Line']}
    RETURN                    ${t}

*** Test Cases ***
ERT Generated Models Run In The RTE
    [Documentation]           Real Embedded Coder code dispatches under the
    ...                       generated RTE: 1 kHz fast group with no
    ...                       overruns (RTE-002), the slow group firing at
    ...                       its divider, no seqlock stale fallbacks
    ...                       (RTE-004) and the DAQ ring streaming (RTE-005).
    Prepare Machine
    Wait For Line On Uart     PicoDesk generated RTE boot
    Read Telemetry
    ${t}=    Read Telemetry
    Telemetry Must Contain    ${t}    telemetry line    hb    dhb    ovr    slf
    ...                       slow_100ms    daq
    Should Be True            900 <= ${t}[dhb] <= 1100    msg=fast rate off: ${t}[dhb]
    Should Be Equal As Integers    ${t}[ovr]    0    msg=overruns with ERT code
    Should Be Equal As Integers    ${t}[slf]    0    msg=seqlock stale fallbacks
    Should Be True            ${t}[slow_100ms] > 0    msg=100 ms group not firing
    Should Be True            ${t}[daq] > 0     msg=DAQ ring not streaming

ERT Cross-Core Loop Closes Through Both Seqlock Buses
    [Documentation]           ThermalModel derates FastCtrl's torque, and
    ...                       FastCtrl's torque drives ThermalModel — through
    ...                       one seqlock bus each way. A nonzero derate
    ...                       proves the slow ERT model consumed fast-loop
    ...                       output and its result reached the fast loop
    ...                       (RTE-001, RTE-004).
    Prepare Machine
    Wait For Line On Uart     PicoDesk generated RTE boot
    Read Telemetry
    Read Telemetry
    ${t}=    Read Telemetry
    Telemetry Must Contain    ${t}    telemetry line
    ...                       FastCtrl_torque_cmd    ThermalModel_derate_pct
    Should Not Be Equal As Integers    ${t}[FastCtrl_torque_cmd]    0
    ...                       msg=ERT fast model produced no output
    Should Be True            ${t}[ThermalModel_derate_pct] > 0
    ...                       msg=cross-core round trip through ERT code broken
