*** Comments ***
Scale validation on the emulated RP2040 (Phase 8).

The SRS scopes the toolchain at 20–30 independent models (§1.1), so release
evidence has to come from a workspace that size — not the two-model fixture.
This runs generated firmware for a 28-model workspace chained across all
three rate groups, so most edges cross a rate boundary and exercise the
seqlock buses rather than plain stores.

Telemetry line (generated by rte_gen.c):
  RTEGEN hb=<n> dhb=<n> exec_max=<n> ovr=<n> slf=<n> slow_10ms=<n>
         slow_100ms=<n> daq=<n> daq_drain=<n> <signal>=<v> ...

*** Settings ***
Suite Setup                   Setup
Suite Teardown                Teardown
Test Teardown                 Test Teardown
Resource                      ${RENODEKEYWORDS}
Resource                      ${CURDIR}${/}telemetry.resource

*** Variables ***
${FIRMWARE}                   ${CURDIR}${/}..${/}build-scale${/}picodesk_gen_firmware.elf

*** Keywords ***
Prepare Machine
    Execute Command           $global.FIRMWARE=@${FIRMWARE}
    Execute Script            ${CURDIR}${/}picodesk_sim.resc
    Create Terminal Tester    sysbus.uart0    timeout=60    defaultPauseEmulation=true

Read Telemetry
    ${line}=    Wait For Line On Uart    RTEGEN hb=
    ${t}=                     Parse Telemetry Fields    ${line['Line']}
    Telemetry Must Contain    ${t}    ${line['Line']}    hb    dhb    ovr    slf
    ...                       slow_10ms    slow_100ms    daq
    RETURN                    ${t}

*** Test Cases ***
Twenty-Eight Model Workspace Dispatches Correctly
    [Documentation]           A full-size workspace boots and runs: the fast
    ...                       group still ticks at 1 kHz with no overruns
    ...                       (RTE-002, BLD-003), both slow groups fire at
    ...                       their dividers, the cross-rate seqlock buses
    ...                       stay fault-free (RTE-004) and the DAQ ring
    ...                       keeps up (RTE-005).
    Prepare Machine
    Wait For Line On Uart     PicoDesk generated RTE boot
    Read Telemetry
    ${t}=    Read Telemetry

    ${hb}=      Set Variable    ${t}[hb]
    ${dhb}=     Set Variable    ${t}[dhb]
    ${ovr}=     Set Variable    ${t}[ovr]
    ${slf}=     Set Variable    ${t}[slf]
    ${s10}=     Set Variable    ${t}[slow_10ms]
    ${s100}=    Set Variable    ${t}[slow_100ms]
    ${daq}=     Set Variable    ${t}[daq]

    Should Be True            900 <= ${dhb} <= 1100
    ...                       msg=fast rate degraded at scale: ${dhb}
    Should Be Equal As Integers    ${ovr}    0
    ...                       msg=fast loop overran with 28 models
    Should Be Equal As Integers    ${slf}    0
    ...                       msg=seqlock stale fallbacks at scale
    Should Be True            ${s10} > 0     msg=10 ms group not firing
    Should Be True            ${s100} > 0    msg=100 ms group not firing
    Should Be True            ${daq} > 0     msg=DAQ ring not streaming
    # Rate-group ratios must still hold with a full workspace.
    Should Be True            ${hb}/15 <= ${s10} <= ${hb}/7
    ...                       msg=10 ms ratio off: ${s10} vs hb ${hb}
    Should Be True            ${hb}/150 <= ${s100} <= ${hb}/70
    ...                       msg=100 ms ratio off: ${s100} vs hb ${hb}

Scale Workspace Signals Propagate Through The Chain
    [Documentation]           The 28 models are chained producer→consumer, so
    ...                       a live signal at the tail proves the whole mesh
    ...                       — including every seqlock bus between rate
    ...                       groups — is actually moving data (RTE-001/004).
    Prepare Machine
    Wait For Line On Uart     PicoDesk generated RTE boot
    Read Telemetry
    ${line}=    Wait For Line On Uart    RTEGEN hb=
    ${values}=    Evaluate
    ...    [int(v) for v in re.findall(r"Model\\d+_y=(-?\\d+)", $line['Line'])]    re
    Should Not Be Empty       ${values}    msg=no model outputs in telemetry
    ${nonzero}=    Evaluate    [v for v in $values if v != 0]
    Should Not Be Empty       ${nonzero}
    ...                       msg=every reported model output stuck at zero
